server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser-db
    username: docker
    password: docker
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true